### ISSUE TITLE
I like where you are going with this

### ISSUE THREAD

**Issue by StuntsPT** [ray2g/BEAST2-StarBEAST2#1]
Just a few comments on the code so far:

1. Do not write a comment above each function stating what it does. Use a proper docstring:

```python
def example_func():
"""
Hi, I'm a proper function docstring! I can be multiline, and I should at least state 3 things:
1. What the function does
2. What the function takes as input
3. What the function returns
"""
```

2. Do not call your function "function" use a descriptive variable name, that hints at what it does from the name. Your future self will thank you.

3. On [line 27](https://github.com/ray2g/StarBeast/blob/master/namefastaseq_changer_2gencode.py#L27) you are naming a variable "input". Don't do this. "input" is a python keyword, and you really don't want to mess your namespace. Use instead "file_handle" to name that var.

I guess that's it. Keep up the god work.

**Comment by ray2g** [comment]
Thank you! 

I'll make the changes and improve the script ;)
